### ISSUE TITLE
Bundling the aws sdk

### ISSUE THREAD

**Issue by hffmnn** [AndrzejKomarnicki/awscdk-nodejsfunction-middy#2]
Hi and thanks a lot for this repository. It helped me a lot when setting up my own middy-based project.

I looked into the bundling of some of the aws-sdk based middlewares and they state:

> To exclude @aws-sdk add @aws-sdk/client-secrets-manager to the exclude list.

I think it is a best practice to not rely on the node runtime provided aws-sdk but bundle it on your own.

So I updated the `bundling` to look like this:

```
bundling: {
        minify: true,
        externalModules: [],
      },
```

Initial bundling (without the `externalModules` set, so it uses the default value of `["@aws-sdk/*"]` produces a bundle size of 92.2kb. When running with `externalModules` set as above, it gives 1.1mb. I tried adding suggestions from here: https://github.com/aws/aws-sdk-js-v3/issues/3023 and especially the `--main-fields=module,main` halves the output again.

```
bundling: {
        minify: true,
        sourcesContent: true,
        mainFields: ["module", "main"],
        externalModules: [],
      },
```

gives 466.4kb.

I think this is still quite big, especially because only there are only dynamo and ssm dependencies. Do you have any other ideas what could reduce the bundle size again. Or do you any ideas when the bundle size has real impact on the cold start duration?

**Comment by AndrzejKomarnicki** [comment]
@hffmnn you might find this recent blog's conclusion about the impact of minification, source maps and bundling to be relevant:

"Conclusion?
The cold start is affected by the size of loaded modules, not the size of the package. The majority of the cold start is not downloading the package from the S3; it’s Node.js loading the code."

Source: https://betterdev.blog/lambda-code-minification/

**Comment by hffmnn** [comment]
Thanks a lot for the blog post. Really interesting.
